-- Initialize tables for syncing local sqlite data to Supabase Postgres.
-- Execute in Supabase SQL Editor before running migration scripts.

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_users_email
ON public.users (email);

CREATE TABLE IF NOT EXISTS public.auth_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user
ON public.auth_sessions (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_expire
ON public.auth_sessions (expires_at);

CREATE TABLE IF NOT EXISTS public.favorite_songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  song_id TEXT NOT NULL,
  song_title TEXT NOT NULL,
  album_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE (user_id, song_id)
);

CREATE INDEX IF NOT EXISTS idx_favorite_songs_user_created
ON public.favorite_songs (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.playlist_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  playlist_id TEXT NOT NULL,
  song_id TEXT NOT NULL,
  song_title TEXT NOT NULL,
  album_name TEXT NOT NULL,
  position INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE (user_id, playlist_id, song_id)
);

CREATE INDEX IF NOT EXISTS idx_playlist_items_user_playlist_pos
ON public.playlist_items (user_id, playlist_id, position);

CREATE TABLE IF NOT EXISTS public.playback_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  song_id TEXT NOT NULL,
  song_title TEXT NOT NULL,
  album_name TEXT NOT NULL,
  event TEXT NOT NULL,
  position_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  played_seconds DOUBLE PRECISION NOT NULL DEFAULT 0,
  duration_seconds DOUBLE PRECISION,
  pathname TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT '',
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_playback_logs_song_created_at
ON public.playback_logs (song_id, created_at);

CREATE INDEX IF NOT EXISTS idx_playback_logs_event_created_at
ON public.playback_logs (event, created_at);

CREATE INDEX IF NOT EXISTS idx_playback_logs_user_created_at
ON public.playback_logs (user_id, created_at);
